-   id: pii_secret_filename
    name: Check filenames for potential secrets
    description: 'Check filenames for potential secrets'
    language: python
    entry: pii-secret-filename

-   id: pii_secret_file_content
    name: Check file content for potential secrets
    description: 'Check file content for potential secrets'
    language: python
    entry: pii-secret-file-content

-   id: hooks_version_check
    name: Check repository version
    description: 'Check repository version'
    language: python
    entry: pii-secret-file-version-check

-   id: pii_secret_file_content_ner
    name: PII Named Entity Recognition
    description: 'Check for PII content with Named Entity Recognition'
    language: python
    entry: pii-secret-file-content-ner
