repos:
-   repo: https://github.com/uktrade/pii-secret-check-hooks
    rev: main
    hooks:
    -   id: pii_secret_filename
        files: ''
        language: python
        pass_filenames: true
        require_serial: true
    -   id: pii_secret_file_content
        files: ''
        language: python
        pass_filenames: true
        require_serial: true
    -   id: pii_secret_file_content_ner
        files: ''
        language: python
        pass_filenames: true
        require_serial: true
    -   id: hooks_version_check
        name: Checking local hooks against latest release
        verbose: true
        require_serial: true
